from typing import Any, Dict
from eth_typing import URI, HexStr
from web3._utils.request import async_get_response_from_get_request, async_json_make_get_request
from web3.beacon.api_endpoints import GET_ATTESTATIONS, GET_ATTESTER_SLASHINGS, GET_BEACON_HEADS, GET_BEACON_STATE, GET_BLINDED_BLOCKS, GET_BLOCK, GET_BLOCK_ATTESTATIONS, GET_BLOCK_HEADER, GET_BLOCK_HEADERS, GET_BLOCK_ROOT, GET_BLS_TO_EXECUTION_CHANGES, GET_DEPOSIT_CONTRACT, GET_EPOCH_COMMITTEES, GET_EPOCH_RANDAO, GET_EPOCH_SYNC_COMMITTEES, GET_FINALITY_CHECKPOINT, GET_FORK_DATA, GET_FORK_SCHEDULE, GET_GENESIS, GET_HASH_ROOT, GET_HEALTH, GET_LIGHT_CLIENT_BOOTSTRAP_STRUCTURE, GET_LIGHT_CLIENT_FINALITY_UPDATE, GET_LIGHT_CLIENT_OPTIMISTIC_UPDATE, GET_LIGHT_CLIENT_UPDATES, GET_NODE_IDENTITY, GET_PEER, GET_PEERS, GET_PROPOSER_SLASHINGS, GET_REWARDS, GET_SPEC, GET_SYNCING, GET_VALIDATOR, GET_VALIDATOR_BALANCES, GET_VALIDATORS, GET_VERSION, GET_VOLUNTARY_EXITS


class AsyncBeacon:
    is_async = True

    def __init__(self, base_url: str, request_timeout: float=10.0) ->None:
        self.base_url = base_url
        self.request_timeout = request_timeout
